train: /Users/miguelpiffer/Desktop/estudos/projeto integrador/imagens/train/images
val: /Users/miguelpiffer/Desktop/estudos/projeto integrador/imagens/valid/images
test: /Users/miguelpiffer/Desktop/estudos/projeto integrador/imagens/test/images

nc: 1
names: ['amendoim']

roboflow:
  workspace: mlai-project-xz
  project: peanuts-hkze4
  version: 3
  license: CC BY 4.0
  url: https://universe.roboflow.com/mlai-project-xz/peanuts-hkze4/dataset/3  
